### ISSUE TITLE
Add options for pre-/post-run scripts

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/ripsaw#197]
A user running a set of workloads may need to execute additional custom commands or scripts between test runs or iterations. We may have a library of such shared scripts, perhaps stored in the snafu repository, for reuse among different workloads. One major driver for this functionality is the need to drop system page cache and ceph OSD cache for any IO-centric workloads.

For flexibility, I would recommend that this is implemented across our CRs universally as something like this:

```yaml
spec:
  workload:
    sample_pre_script: https://my.url
    sample_post_script: https://my.url
    run_pre_script: https://my.url
    run_post_script: https://my.url
```

Where the `sample_` scripts would be slotted in around the sample/iteration logic (innermost loop) and the `run_` scripts would be placed around the workload's outermost loop.

With scripts hosted in snafu, the URL could point directly to the raw file:
`https://raw.githubusercontent.com/cloud-bulldozer/snafu/master/pre-post-scripts/drop_caches.py`

**Comment by dustinblack** [comment]
@bengland2 recommended that the scripts values should be a list so that multiple can be provided, and I tend to agree. So the structure would be more like:

```yaml
spec:
  workload:
    sample_pre_scripts:
      - https://my.url
    sample_post_scripts:
      - https://my.url
    run_pre_scripts:
      - https://my.url
    run_post_scripts:
      - https://my.url
```
