### ISSUE TITLE
RFE: Central collection point for results

### ISSUE THREAD

**Issue by dustinblack** [cloud-bulldozer/ripsaw#26]
Add a feature to tag workload results and upload them to a central repository (likely an object store). Could be configurable as a private repo, or could default to a public one where we can collect broad result sets for analysis.

**Comment by jtaleric** [comment]
I am re-iterating on this idea.

Current idea:
Create shared pvc `deploy/result-pvc.yaml`
```yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: result-volume
spec:
   accessModes:
     - ReadWriteMany
   resources:
     requests:
       storage: 1Gi
```

Since we are moving to template our workloads, this would be simple to implement...

```yaml
---

apiVersion: batch/v1
kind: "job"
metadata:
  name: "{{ meta.name }}-sysbench"
  namespace: "{{ meta.namespace }}"
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
       app: sysbench
    spec:
      containers:
      - name: sysbench
        command: ["/bin/sh", "-c"]
        args: ["/tmp/sysbenchScript"]
        image: "docker.io/smalleni/centos-sysbench:latest"
        volumeMounts:
        - name: sysbench-volume
          mountPath: "/tmp/"
{% if store_results %}
        - name: result-data
          mountPath: "{{results.path}}"
{% endif %}
      volumes:
      - name: sysbench-volume
        configMap:
          name: "{{ meta.name }}-sysbench-config"
          defaultMode: 0777
{% if store_results %}
      - name: result-data
        persistentVolumeClaim:
          claimName: result-volume
{% endif %}
      restartPolicy: OnFailure
```

The output needs to be _sent_ to the share location
Again, modifying the template `roles/sysbench/templates/sysbench.sh.j2`
```
...
sysbench --test={{test.name}} \
  {% for opt,value in test.parameters.iteritems() %}
  --{{opt}}={{value}} \
  {% endfor %}
  run {% if store_results %} \
  | tee {{results.path}}/stdout {% endif %}
...
```

To enable this feature, it is in our CR
```
  store_results: true
  results:
    path: /opt/results/
```

This just gets the Operator to wearhouse the data... Next step is to add a elasticsearch connector and index the data... Create a parser, etc.
