### ISSUE TITLE
RFE : New CR / Playbook structure

### ISSUE THREAD

**Issue by jtaleric** [cloud-bulldozer/ripsaw#7]
Right now our Custom resource looks like 
```yaml
spec:
  uperf:
    # To disable uperf, set pairs to 0
    pair: 1
    proto: tcp
    test_type: stream
    nthr: 2
    size: 16384
    runtime: 10
  fio:
    # To disable fio, set clients to 0
    clients: 0
    jobname: test-write
    bs: 4k
    iodepth: 4
    runtime: 57
    rw: write
    filesize: 1
```

We only have a limited definition. I would like to move to a list

```yaml
spec:
    infra:
      couchbase:
        servers: 1
    workloads:
      - uperf:
        # To disable uperf, set pairs to 0
        pair: 1
        ...
     - fio:
       # To disable fio, set clients to 0
       clients: 0
       jobname: test-write
     - ycsb:
       ...
```

Which would allow us to have a pipeline of workloads that we iterate through.

Also, defining the infrastructure (ie databases we will run against) allows us to kick off infrastructure and run many different workloads against it, vs just always relying on YCSB...

**Comment by dustinblack** [comment]
+1
This should offer a lot more flexibility and at this point in development should be trivial to change.

Just brainstorming... Is there any need to segregate workload types that require some underlying infra (i.e., ycsb, hammerdb, dvdstore) vs those that operate on the core ocp/k8s substrate (i.e., uperf, fio)?

**Comment by jtaleric** [comment]
@dustinblack Not sure if we want to segregate them... For example, I have also been thinking about infrastructure like SRIOV -- If we define we need SRIOV configured within the infra, the workloads could possibly take advantage of that. 

```yaml
spec:
  infra:
    sriov:
      vfs: 10 # spit balling here
  workloads:
    - uperf:
      sriov: enabled # for example?
```

Again, I haven't hashed out all the different infra needs we might have...

**Comment by portante** [comment]
I assume what ever is listed under "workloads" has to be valid/support workloads defined somewhere?

And assume you don't have to list everything, just the workloads you want to run?

**Comment by jtaleric** [comment]
@portante yes, it is here : https://github.com/jtaleric/benchmark-operator#workloads

**Comment by aakarshg** [comment]
I've a minor concern about the case that might occur in future when multiple workloads can make use of same infra, we'll need to keep it in mind when we move on with this.

**Comment by jtaleric** [comment]
@aakarshg nothing is stating we would have to reuse the same infra per workload -- again this is quite fluid, so feel free to put your .02 into the structure

**Comment by aakarshg** [comment]
Given that we would like to encourage users to run only one workload at once, following would be how I suggest we move forward with CR:
```yaml
spec:
  infra: 
    name: couchbase
    args:
      servers:
        size: 1
      storage:
        use_persistent_storage: False
  workload: 
    name: ycsb
    args:
      workers: 1
      infra: couchbase
      driver: couchbase2
      workload: workloada
```
